# -*- coding: utf-8 -*-
"""personal_loan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ByXdqNujmfSsKZTrqDWDV90L1ZdQQDE_

Imporing libraries
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

"""Reading data"""

data = pd.read_csv("Bank_Personal_Loan_Modelling.csv")

print(data)

data.drop(["ZIP Code", "ID"], axis=1, inplace=True)

print(data)

"""Splitting data"""

y = data[("Personal Loan")]
X = data.drop("Personal Loan", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=5)

print(X_train.shape)
print(X_test.shape)

"""Building Model...........

Logistic regression
"""

regressor = LogisticRegression()

regressor.fit(X_train, y_train)

X_train_pred = regressor.predict(X_train)
X_test_pred = regressor.predict(X_test)

accuracy_score(y_train,X_train_pred)

accuracy_score(y_test,X_test_pred)

"""Decision Tree"""

from sklearn.tree import DecisionTreeClassifier

DT=DecisionTreeClassifier()

DT.fit(X_train,y_train)

X_train_pred=DT.predict(X_train)
X_test_pred=DT.predict(X_test)

accuracy_score(y_train,X_train_pred)

accuracy_score(y_test,X_test_pred)

"""SVM"""

from sklearn import svm 
model1=svm.SVC(C=0.00001,kernel='linear')
model1.fit(X_train,y_train)

model1.coef_

model1.intercept_

X_train_pred=model1.predict(X_train)
X_test_pred=model1.predict(X_test)

accuracy_score(y_train,X_train_pred)

accuracy_score(y_test,X_test_pred)

"""saving model as pkl file.."""

pickle.dump(regressor, open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))